In [1]:
import pandas as pd
import numpy as np

In [76]:
#read file type of vehicle
vehicle = pd.read_csv('vehicles_in_accident.csv', sep=';')

In [77]:
vehicle

,Codi_expedient,Descripcio_causa_vianant,Descripcio_tipus_vehicle,Descripcio_model,Descripcio_marca,Descripcio_color
0,2018S007344,No Ã©s causa del vianant,Turisme,CORDOBA,SEAT,Blanc
1,2018S009617,No Ã©s causa del vianant,Turisme,206,PEUGEOT,Blau
2,2018S008382,No Ã©s causa del vianant,"CamiÃ³ rÃ­gid > 3,5 tones",Desconegut,DAF-HERMANNS,Taronja
3,2018S002684,No Ã©s causa del vianant,"CamiÃ³ rÃ­gid > 3,5 tones",ML140E24 E,IVECO FIAT,Blanc
4,2018S004886,No Ã©s causa del vianant,Taxi,TOLEDO,SEAT,Negre/Groc
...,...,...,...,...,...,...
19074,2018S006251,No Ã©s causa del vianant,Turisme,VECTRA,OPEL,Platejat
19075,2018S006492,No Ã©s causa del vianant,Turisme,307,PEUGEOT,Gris
19076,2018S006492,No Ã©s causa del vianant,Turisme,C4,CITROEN,Negre
19077,2018S006492,No Ã©s causa del vianant,Turisme,MINI COOPER,MINI,Desconegut
19078,2018S009754,No Ã©s causa del vianant,Turisme,A4,AUDI,Vermell

In [78]:
vehicle[vehicle.Descripcio_tipus_vehicle == 'CamiÃ³ rÃ­gid > 3,5 tones']

,Codi_expedient,Descripcio_causa_vianant,Descripcio_tipus_vehicle,Descripcio_model,Descripcio_marca,Descripcio_color
2,2018S008382,No Ã©s causa del vianant,"CamiÃ³ rÃ­gid > 3,5 tones",Desconegut,DAF-HERMANNS,Taronja
3,2018S002684,No Ã©s causa del vianant,"CamiÃ³ rÃ­gid > 3,5 tones",ML140E24 E,IVECO FIAT,Blanc
121,2018S000016,No Ã©s causa del vianant,"CamiÃ³ rÃ­gid > 3,5 tones",Desconegut,IVECO FIAT,Blanc
185,2018S000128,No Ã©s causa del vianant,"CamiÃ³ rÃ­gid > 3,5 tones",,ES DESCONEIX,Blau
254,2018S000645,No Ã©s causa del vianant,"CamiÃ³ rÃ­gid > 3,5 tones",,M.A.N.,Desconegut
...,...,...,...,...,...,...
18416,2018S002541,No Ã©s causa del vianant,"CamiÃ³ rÃ­gid > 3,5 tones",AD260S27Y/,IVECO FIAT,Blanc
18518,2018S004847,No Ã©s causa del vianant,"CamiÃ³ rÃ­gid > 3,5 tones",STRALIS,IVECO FIAT,Blanc
18871,2018S009224,No Ã©s causa del vianant,"CamiÃ³ rÃ­gid > 3,5 tones",Desconegut,IVECO BUS,Desconegut
18901,2018S000880,No Ã©s causa del vianant,"CamiÃ³ rÃ­gid > 3,5 tones",Desconegut,MERCEDES,Blanc
19002,2018S002542,No Ã©s causa del vianant,"CamiÃ³ rÃ­gid > 3,5 tones",STRALIS,IVECO FIAT,Blanc

In [80]:
vehicle = vehicle.drop('Descripcio_causa_vianant',axis=1)

In [81]:
vehicle.columns=['accident_id','type_vehicle','model','brand','color']
vehicle

,accident_id,type_vehicle,model,brand,color
0,2018S007344,Turisme,CORDOBA,SEAT,Blanc
1,2018S009617,Turisme,206,PEUGEOT,Blau
2,2018S008382,"CamiÃ³ rÃ­gid > 3,5 tones",Desconegut,DAF-HERMANNS,Taronja
3,2018S002684,"CamiÃ³ rÃ­gid > 3,5 tones",ML140E24 E,IVECO FIAT,Blanc
4,2018S004886,Taxi,TOLEDO,SEAT,Negre/Groc
...,...,...,...,...,...
19074,2018S006251,Turisme,VECTRA,OPEL,Platejat
19075,2018S006492,Turisme,307,PEUGEOT,Gris
19076,2018S006492,Turisme,C4,CITROEN,Negre
19077,2018S006492,Turisme,MINI COOPER,MINI,Desconegut
19078,2018S009754,Turisme,A4,AUDI,Vermell

In [82]:
vehicle.to_csv('vehicles_in_accident_formatted.csv')

In [83]:
type_of_accident = pd.read_csv('type_accident.csv',sep=';')
type_of_accident

        Codi_expedient                Tipus_accident
0      2018S000001                    Abast multiple
1      2018S000002         Col.lisiÃ³ fronto-lateral
2      2018S000003                             Abast
3      2018S000004       Xoc contra element estÃ tic
4      2018S000005      Bolcada (mÃ©s de dues rodes)
...                ...                           ...
10546  2018S009968                Col.lisiÃ³ lateral
10547  2018S009969                             Abast
10548  2018S009971                Col.lisiÃ³ frontal
10549  2018S009972          Caiguda interior vehicle
10550  2018S009973         Col.lisiÃ³ fronto-lateral

[10551 rows x 2 columns]

In [45]:
cause_accident = pd.read_csv('causes_accident.csv',sep = ';')
cause_accident

      Codi_expedient Descripcio_causa_mediata
0    2018S000008       No hi ha causa mediata
1    2018S000021       No hi ha causa mediata
2    2018S000024       No hi ha causa mediata
3    2018S000026       No hi ha causa mediata
4    2018S000031       No hi ha causa mediata
..               ...                      ...
862  2018S009897       No hi ha causa mediata
863  2018S009921       No hi ha causa mediata
864  2018S009949       No hi ha causa mediata
865  2018S009962       No hi ha causa mediata
866  2018S009968       No hi ha causa mediata

[867 rows x 2 columns]

In [84]:
type_cause_accident = pd.merge(type_of_accident,cause_accident, on = 'Codi_expedient', how = 'left')

In [85]:
type_cause_accident

        Codi_expedient                Tipus_accident Descripcio_causa_mediata
0      2018S000001                    Abast multiple                      NaN
1      2018S000002         Col.lisiÃ³ fronto-lateral                      NaN
2      2018S000003                             Abast                      NaN
3      2018S000004       Xoc contra element estÃ tic                      NaN
4      2018S000005      Bolcada (mÃ©s de dues rodes)                      NaN
...                ...                           ...                      ...
10546  2018S009968                Col.lisiÃ³ lateral   No hi ha causa mediata
10547  2018S009969                             Abast                      NaN
10548  2018S009971                Col.lisiÃ³ frontal                      NaN
10549  2018S009972          Caiguda interior vehicle                      NaN
10550  2018S009973         Col.lisiÃ³ fronto-lateral                      NaN

[10551 rows x 3 columns]

In [86]:
type_cause_accident.astype({'Descripcio_causa_mediata':'object'})
type_cause_accident.dtypes

Codi_expedient              object
Tipus_accident              object
Descripcio_causa_mediata    object
dtype: object

In [87]:
type_cause_accident = type_cause_accident.fillna("Not_Specified")
type_cause_accident

        Codi_expedient                Tipus_accident Descripcio_causa_mediata
0      2018S000001                    Abast multiple            Not_Specified
1      2018S000002         Col.lisiÃ³ fronto-lateral            Not_Specified
2      2018S000003                             Abast            Not_Specified
3      2018S000004       Xoc contra element estÃ tic            Not_Specified
4      2018S000005      Bolcada (mÃ©s de dues rodes)            Not_Specified
...                ...                           ...                      ...
10546  2018S009968                Col.lisiÃ³ lateral   No hi ha causa mediata
10547  2018S009969                             Abast            Not_Specified
10548  2018S009971                Col.lisiÃ³ frontal            Not_Specified
10549  2018S009972          Caiguda interior vehicle            Not_Specified
10550  2018S009973         Col.lisiÃ³ fronto-lateral            Not_Specified

[10551 rows x 3 columns]

In [88]:
type_cause_accident.to_csv('type_cause_accident_formated.csv')